version: '3.7' # Updated version for better networking features

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - "38080:8080"
    networks:
      - spark-network

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    ports:
      - "38070:8080" # Port for Spark master web UI
      - "37077:7077" # Spark master service port
    networks:
      - spark-network

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=4g"
    ports:
      - "38081:8081" # Spark worker web UI port
    networks:
      - spark-network

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=4g"
    ports:
      - "38082:8081"
    networks:
      - spark-network

  spark-worker-3:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-3
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=4g"
    ports:
      - "38083:8081"
    networks:
      - spark-network

  jupyter-notebook:
    image: my-custom-pyspark-notebook
    container_name: jupyter-pyspark-notebook
    environment:
      - "JUPYTER_ENABLE_LAB=yes"
      - "SPARK_MASTER=spark://spark-master:37077"
    ports:
      - "38888:8888"
    volumes:
      - "./notebooks:/home/jovyan/work"
      - "C:/Users/SurfaceBook/Desktop/postgresql-42.6.0.jar:/home/jovyan/jars/postgresql-42.6.0.jar"
    networks:
      - spark-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: exampledb
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
    ports:
      - "35432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
      - "C:/Users/SurfaceBook/Downloads/data-csv:/data"
    networks:
      - spark-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "35050:80"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    networks:
      - spark-network

  python-importer:
    image: python:3.8
    depends_on:
      - postgres
    volumes:
      - "C:/Users/SurfaceBook/Downloads/data-csv:/data"
    command: >
      bash -c "sleep 10; python /data/import_script.py"
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  postgres_data: {}
  pgadmin_data: {}
